project_id = "anvjrqgajwvqsceobhtk"

[functions.queue-seo-resolution]
verify_jwt = false

[functions.process-seo-resolution]
verify_jwt = false

[functions.sync-woocommerce-products]
verify_jwt = false

[functions.sync-woocommerce-categories]
verify_jwt = false

[functions.sync-woocommerce-collections]
verify_jwt = false

[functions.mark-issues-manually-resolved]
verify_jwt = false

[functions.get-woocommerce-stats]
verify_jwt = false

[functions.test-woocommerce-connection]
verify_jwt = false

[functions.generate-product-seo]
verify_jwt = false

[functions.generate-alt-texts]
verify_jwt = false

[functions.generate-product-description]
verify_jwt = false

[functions.generate-meta-description]
verify_jwt = false

[functions.translate-product]
verify_jwt = false

[functions.generate-blog-post]
verify_jwt = false

[functions.run-seo-diagnostic]
verify_jwt = false

[functions.resolve-seo-issues]
verify_jwt = false

[functions.get-wordpress-analytics]
verify_jwt = false

[functions.get-wordpress-basic-analytics]
verify_jwt = false

[functions.get-wordpress-jetpack-analytics]
verify_jwt = false

[functions.process-generation-queue]
verify_jwt = false

[functions.add-internal-links]
verify_jwt = false

[functions.format-product-content]
verify_jwt = false

[functions.update-woocommerce-product]
verify_jwt = false

[functions.get-shopify-analytics]
verify_jwt = false

[functions.generate-collection-descriptions]
verify_jwt = false

[functions.generate-long-collection-description]
verify_jwt = false

[functions.generate-short-collection-description]
verify_jwt = false

[functions.publish-collection]
verify_jwt = false

[functions.sync-single-collection]
verify_jwt = false

[functions.update-wordpress-media-alt]
verify_jwt = false

[functions.improve-product-image]
verify_jwt = false

[functions.apply-improved-image]
verify_jwt = false

[functions.ai-niche-research]
verify_jwt = false

[functions.ai-competitor-analysis]
verify_jwt = false

[functions.ai-generate-catalog]
verify_jwt = false

[functions.ai-export-catalog]
verify_jwt = false

[functions.sync-wordpress-posts]
verify_jwt = false

[functions.suggest-blog-topics]
verify_jwt = false
