project_id = "ysrwnhhbcvjsjwecezdf"

[functions.get-wordpress-analytics]
verify_jwt = true

[functions.get-wordpress-basic-analytics]
verify_jwt = true

[functions.get-shopify-analytics]
verify_jwt = true