// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysrwnhhbcvjsjwecezdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzcnduaGhiY3Zqc2p3ZWNlemRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NzE3MTQsImV4cCI6MjA3MzQ0NzcxNH0.YTRWE7Ewp2LS3esyQXZbwo2KOp6dvCd8-tNDtpCY7AA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});