// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anvjrqgajwvqsceobhtk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFudmpycWdhand2cXNjZW9iaHRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0Mzg2ODYsImV4cCI6MjA3NjAxNDY4Nn0.5Hc5TtCPqqNW_91H98OsmMzgpcqGRsw3KyTfoFnNw5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});